### ISSUE TITLE
Make Clear source configurable

### ISSUE THREAD

**Issue by CodeTheory** [wulkano/clear#7]
@doot0 

Here's a few of the things we should make configurable. Let's extend this list as time goes on before release.

- [x] Default font type. Either `serif`, `sans-serif` or `mono` will make the default font fallback the most common fallbacks for any of those font types

**Comment by doot0** [comment]
`Sans-serif` should be sensible default for sure.

**Comment by CodeTheory** [comment]
@doot0 I've set sans-serif as a default, but will make suggestions for other fonts in the docs.
